// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//   find the sum of the even-valued terms.

//Counting
//  prev = 1
//  curr = 2
//  temp = prev + curr;
//  prev = curr
//  curr = temp

// while curr <= 4 mill

const fibo = () => {
  let prev = 1;
  let curr = 2;
  let temp,sum=0;
  while(curr<4000000){
    temp = prev + curr;
    prev = curr;
    curr = temp;
    prev%2==0?sum+=prev:null
  }
  return sum;
}
console.log(fibo());